In [44]:
import numpy as np
import sympy as sp
import math
import matplotlib.pyplot as plt
%matplotlib qt

From https://gist.github.com/Nikolaj-K/11233e5d4331f0e1e8b569f9a1481d60

In [52]:
def polar_to_kartesian(r, theta, phi):
    x = np.sin(theta)*np.cos(phi)
    z = np.cos(theta) * -1
    y = np.sin(theta)*np.sin(phi)
    
    #x = r * np.sin(theta)*np.cos(phi)
    #y = -r * np.sin(theta)*np.sin(phi)
    #z = -r * np.cos(theta)

    return [x,y,z]

In [102]:
def runge_kutta4(y, t, dt, f):
    """computes 4th order Runge-Kutta for dy/dt.

    Parameters
    ----------

    y : scalar
        Initial/current value for y
    x : scalar
        Initial/current value for x
    dx : scalar
        difference in x (e.g. the time step)
    f : ufunc(y,x)
        Callable function (y, x) that you supply to compute dy/dx for
        the specified values.
    """
    y = np.array(y)
    k1 = dt * f(y, t)
    print(y.shape, k1.shape)
    k2 = dt * f(y + 0.5 * k1, t+0.5*dt)
    k3 = dt * f(y + 0.5 * k2, t+0.5*dt)
    k4 = dt * f(y + k3, t + dt)
    #k1 = dt * f(y, t)
    #k1 = [a * dt for a in f(y,t)]
    print(k1)
    #k2 = [a * dt for a in f([sum(c) for c in zip(y,[b * 0.5 for b in k1])], t + 0.5 * dt)]
    #k3 = [a * dt for a in f([sum(c) for c in zip(y,[b * 0.5 for b in k2])], t + 0.5 * dt)]
    #k4 = [a * dt for a in f([sum(c) for c in zip(y,k3)], t + dt)]
    
    
    return y + (k1 + 2*k2 + 2*k3 + k4) / 6.

In [124]:
def g(y):
    print(y)
    theta, phi, d_theta, d_phi = y
    c, s, t = np.cos(theta), np.sin(theta), np.tan(theta)

    d2_theta = (d_phi**2 * c - gravitation / l) * s
    d2_phi = -2 * d_theta * d_phi / t
    if (t == 0):
            print ('t is 0')

    return np.array([d2_theta, d2_phi])

#y = [theta, phi, d_theta, d_phi] 
def f(y, t):
    dq = y[2:]

    dq2 = g(y)
    return np.concatenate([dq, dq2])
    
def integrate(f, dt, y_init, t_init=0, t_fin=float('inf')):
    # Solves y'(t) = f(t, y) for a seqeunce of ys.
    y_s = []
    t_s = []
    
    y = y_init
    t = t_init
    y_s.append(y)
    t_s.append(t)
    while t < t_fin:

        y += runge_kutta4(y, t, dt, f)
        t += dt
        y_s.append(y)
        t_s.append(t)
        
    return y_s, t_s

In [125]:
DEG_TO_RAD = math.pi/180
RAD_TO_DEG = 180/math.pi

theta = 45 * DEG_TO_RAD
phi = 90* DEG_TO_RAD
theta_first_deriv = 0
phi_first_deriv = 0.1

Y = [
    theta, 
    phi, 
    theta_first_deriv,
    phi_first_deriv
]

theta_second_deriv = [0]
phi_second_deriv = [0]

positions = []
Ts = 0.1
N = 100000
T = np.arange(0,N, Ts)
#T = np.linspace(0,N, 1000 )
gravitation = 9.81
l = 1


pendulum_values = integrate(f, 0.1, Y, t_fin=100)


[0.78539816 1.57079633 0.         0.1       ]
(4,) (4,)
[ 0.78539816  1.57579633 -0.34658588  0.1       ]
[ 0.76806887  1.57579633 -0.34658588  0.10346586]
[ 0.75073958  1.58114291 -0.68101242  0.10742494]
[ 0.          0.01       -0.69317175 -0.        ]
[ 1.53634039  3.15183193 -0.68503046  0.20739932]
(4,) (4,)
[ 1.50208887  3.1622019  -1.17516528  0.20788905]
[ 1.47758213  3.16222638 -1.17422516  0.20908052]
[ 1.41891788  3.17273998 -1.66136652  0.21198958]
[-6.85030463e-02  2.07399321e-02 -9.80269637e-01  9.79451933e-04]
[ 2.95526116  6.32455266 -2.34652023  0.41940962]
(4,) (4,)
[ 2.83793515  6.34552314 -2.43898903 -0.10263683]
[ 2.83331171  6.31942082 -2.49333608  0.49929839]
[ 2.70592755  6.3744825  -2.65138395 -0.3624932 ]
[-0.23465202  0.04194096 -0.18493761 -1.04409291]
[ 5.66281308 12.66327599 -4.99319895  0.52625199]
(4,) (4,)
[ 5.41315313 12.68958858 -4.71460247  0.15847212]
[ 5.42708295 12.67119959 -4.6189043   0.46322418]
[ 5.20092265 12.7095984  -4.26287744  0.15493775

<ipython-input-124-f6ef5fe4261d>:6: RuntimeWarning: overflow encountered in double_scalars
  d2_theta = (d_phi**2 * c - gravitation / l) * s
<ipython-input-124-f6ef5fe4261d>:7: RuntimeWarning: overflow encountered in double_scalars
  d2_phi = -2 * d_theta * d_phi / t
<ipython-input-124-f6ef5fe4261d>:4: RuntimeWarning: invalid value encountered in cos
  c, s, t = np.cos(theta), np.sin(theta), np.tan(theta)
<ipython-input-124-f6ef5fe4261d>:4: RuntimeWarning: invalid value encountered in sin
  c, s, t = np.cos(theta), np.sin(theta), np.tan(theta)
<ipython-input-124-f6ef5fe4261d>:4: RuntimeWarning: invalid value encountered in tan
  c, s, t = np.cos(theta), np.sin(theta), np.tan(theta)
<ipython-input-102-c57f79bb9d4a>:31: RuntimeWarning: invalid value encountered in add
  return y + (k1 + 2*k2 + 2*k3 + k4) / 6.



[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]


[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]


[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
(4,) (4,)
[nan nan nan nan]
[nan nan nan nan]


In [126]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

## Plot

In [127]:
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as p3
import matplotlib.animation as animation

In [128]:
positions = np.array(positions)


In [129]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.set_xlim3d(-2, 2)
ax.set_ylim3d(-2, 2)
ax.set_zlim3d(-2, 2)
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")

string = plt.quiver(0,0,0,0,0,0)

# plotting the overall curve
ax.scatter(positions[:,0], positions[:,1], positions[:,2], c='b', marker='.', linewidth=0.001)

def func(num, positions, pendulum): 
    x = positions[num, 0]
    y = positions[num, 1]
    z = positions[num, 2]
    
    pendulum.set_data(x,y)
    pendulum.set_3d_properties(z)
    
    
        # Plotting the Tangential vector
    u = positions[num, 0]
    v = positions[num, 1]
    w = positions[num, 2]
    
    global string
    string.remove()
    string = plt.quiver(0,0,0, u, v, w,color='g')
    
pendulum, = plt.plot([positions[0,0]], [positions[0,1]], [positions[0,2]], c='r', marker='o')

ani = animation.FuncAnimation(fig, func, frames=N, fargs=(positions, pendulum), interval=1/60, blit=False)

#ax.plot(positions[:,0], positions[:,1], positions[:,2])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [8]:
theta_second_deriv

[0,
 -0.06436717523440032,
 -0.06436717523440032,
 -0.06436672744912167,
 -0.06436583187239445,
 -0.06436448849497751,
 -0.06436269730455943,
 -0.0643604582857599,
 -0.06435777142013167,
 -0.06435463668616305,
 -0.06435105405928078,
 -0.06434702351185362,
 -0.0643425450131964,
 -0.06433761852957445,
 -0.06433224402420869,
 -0.06432642145728124,
 -0.06432015078594153,
 -0.06431343196431284,
 -0.06430626494349945,
 -0.06429864967159431,
 -0.06429058609368721,
 -0.06428207415187341,
 -0.06427311378526288,
 -0.06426370492998994,
 -0.06425384751922364,
 -0.06424354148317828,
 -0.06423278674912483,
 -0.0642215832414026,
 -0.06420993088143159,
 -0.0641978295877252,
 -0.06418527927590355,
 -0.06417227985870733,
 -0.06415883124601203,
 -0.06414493334484285,
 -0.06413058605938994,
 -0.06411578929102432,
 -0.0641005429383141,
 -0.06408484689704153,
 -0.06406870106022006,
 -0.06405210531811241,
 -0.06403505955824884,
 -0.06401756366544598,
 -0.06399961752182616,
 -0.06398122100683734,
 -0.06396237

## Plot first deriv


In [12]:
%matplotlib qt
plt.plot(T, phi_second_deriv)

In [29]:
theta_second_deriv

[0,
 -6.9367175234400325,
 -6.9367175234400325,
 -6.439240446671234,
 -5.353912225909332,
 -3.5855547307789903,
 -1.1500635007790745,
 1.7081690993927208,
 4.521693722005852,
 6.800718836153289,
 8.295415226759802,
 9.075680411103855,
 9.375857979825684,
 9.375873237053616,
 9.064520438820644,
 8.206371904566277,
 6.415030296900763,
 3.3872546479941414,
 -0.704025485860634,
 -4.959888519889868,
 -8.15414073533878,
 -9.637300793191185,
 -9.72446968579181,
 -9.195454712877963,
 -8.691057388080145,
 -8.528988730154888,
 -8.771229543488419,
 -9.29128970562496,
 -9.759786024598576,
 -9.57969701532677,
 -7.909118018129657,
 -4.054002626391581,
 1.6093627729253508,
 7.0109587530388175,
 9.685681817113766,
 9.088989851259946,
 6.590884070577782,
 3.6323315757357513,
 0.8601713895061642,
 -1.634367965780283,
 -3.9459513484949538,
 -6.144631755361892,
 -8.143134845908342,
 -9.556764555233048,
 -9.578774304559959,
 -7.121624308671066,
 -1.7158220775734525,
 4.976366824256905,
 9.330986097765388,


In [10]:
plt.plot(T, theta_second_deriv)

In [ ]:
for i in range(1,len(T)): 

    t_s_d = ((phi_first_deriv[i-1]**2)*(np.cos(theta[i-1]))*(np.sin(theta[i-1]))) - ((g/l) * np.sin(theta[i-1])) *Ts
    theta_second_deriv.append(t_s_d)

    t_f_d = theta_first_deriv[i-1] + t_s_d * Ts
    theta_first_deriv.append(t_f_d)
    
    #p_s_d = -2*theta_first_deriv[i-1]*phi_first_deriv[i-1]*(1/np.tan(theta[i-1]))
    p_s_d = (-2*theta_first_deriv[i-1]*phi_first_deriv[i-1]*np.cos(theta[i-1]))/np.sin(theta[i-1]) * Ts
    phi_second_deriv.append(p_s_d)
    
    p_f_d = phi_first_deriv[i-1] + p_s_d * Ts
    phi_first_deriv.append(p_f_d)
    
    theta.append(theta[i-1] + theta_first_deriv[i-1] * Ts)
    phi.append(phi[i-1] + phi_first_deriv[i-1] * Ts)
    
# Convert to kartesian coordinates
for i in range(0,N-1):
    positions.append(polar_to_kartesian(l, theta[i], phi[i]))
    